// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Pineapple217/Sortify/web/ent/predicate"
	"github.com/Pineapple217/Sortify/web/ent/session"
	"github.com/Pineapple217/Sortify/web/ent/user"
)

// SessionUpdate is the builder for updating Session entities.
type SessionUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (su *SessionUpdate) Where(ps ...predicate.Session) *SessionUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetToken sets the "token" field.
func (su *SessionUpdate) SetToken(s string) *SessionUpdate {
	su.mutation.SetToken(s)
	return su
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (su *SessionUpdate) SetNillableToken(s *string) *SessionUpdate {
	if s != nil {
		su.SetToken(*s)
	}
	return su
}

// SetIPAddress sets the "ip_address" field.
func (su *SessionUpdate) SetIPAddress(s string) *SessionUpdate {
	su.mutation.SetIPAddress(s)
	return su
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (su *SessionUpdate) SetNillableIPAddress(s *string) *SessionUpdate {
	if s != nil {
		su.SetIPAddress(*s)
	}
	return su
}

// ClearIPAddress clears the value of the "ip_address" field.
func (su *SessionUpdate) ClearIPAddress() *SessionUpdate {
	su.mutation.ClearIPAddress()
	return su
}

// SetUserAgent sets the "user_agent" field.
func (su *SessionUpdate) SetUserAgent(s string) *SessionUpdate {
	su.mutation.SetUserAgent(s)
	return su
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (su *SessionUpdate) SetNillableUserAgent(s *string) *SessionUpdate {
	if s != nil {
		su.SetUserAgent(*s)
	}
	return su
}

// ClearUserAgent clears the value of the "user_agent" field.
func (su *SessionUpdate) ClearUserAgent() *SessionUpdate {
	su.mutation.ClearUserAgent()
	return su
}

// SetExpiresAt sets the "expires_at" field.
func (su *SessionUpdate) SetExpiresAt(t time.Time) *SessionUpdate {
	su.mutation.SetExpiresAt(t)
	return su
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (su *SessionUpdate) SetNillableExpiresAt(t *time.Time) *SessionUpdate {
	if t != nil {
		su.SetExpiresAt(*t)
	}
	return su
}

// SetLastLoginAt sets the "last_login_at" field.
func (su *SessionUpdate) SetLastLoginAt(t time.Time) *SessionUpdate {
	su.mutation.SetLastLoginAt(t)
	return su
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (su *SessionUpdate) SetNillableLastLoginAt(t *time.Time) *SessionUpdate {
	if t != nil {
		su.SetLastLoginAt(*t)
	}
	return su
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (su *SessionUpdate) ClearLastLoginAt() *SessionUpdate {
	su.mutation.ClearLastLoginAt()
	return su
}

// SetSpotifyAccessToken sets the "spotify_access_token" field.
func (su *SessionUpdate) SetSpotifyAccessToken(s string) *SessionUpdate {
	su.mutation.SetSpotifyAccessToken(s)
	return su
}

// SetNillableSpotifyAccessToken sets the "spotify_access_token" field if the given value is not nil.
func (su *SessionUpdate) SetNillableSpotifyAccessToken(s *string) *SessionUpdate {
	if s != nil {
		su.SetSpotifyAccessToken(*s)
	}
	return su
}

// ClearSpotifyAccessToken clears the value of the "spotify_access_token" field.
func (su *SessionUpdate) ClearSpotifyAccessToken() *SessionUpdate {
	su.mutation.ClearSpotifyAccessToken()
	return su
}

// SetSpotifyRefreshToken sets the "spotify_refresh_token" field.
func (su *SessionUpdate) SetSpotifyRefreshToken(s string) *SessionUpdate {
	su.mutation.SetSpotifyRefreshToken(s)
	return su
}

// SetNillableSpotifyRefreshToken sets the "spotify_refresh_token" field if the given value is not nil.
func (su *SessionUpdate) SetNillableSpotifyRefreshToken(s *string) *SessionUpdate {
	if s != nil {
		su.SetSpotifyRefreshToken(*s)
	}
	return su
}

// ClearSpotifyRefreshToken clears the value of the "spotify_refresh_token" field.
func (su *SessionUpdate) ClearSpotifyRefreshToken() *SessionUpdate {
	su.mutation.ClearSpotifyRefreshToken()
	return su
}

// SetSpotifyExpiry sets the "spotify_expiry" field.
func (su *SessionUpdate) SetSpotifyExpiry(t time.Time) *SessionUpdate {
	su.mutation.SetSpotifyExpiry(t)
	return su
}

// SetNillableSpotifyExpiry sets the "spotify_expiry" field if the given value is not nil.
func (su *SessionUpdate) SetNillableSpotifyExpiry(t *time.Time) *SessionUpdate {
	if t != nil {
		su.SetSpotifyExpiry(*t)
	}
	return su
}

// ClearSpotifyExpiry clears the value of the "spotify_expiry" field.
func (su *SessionUpdate) ClearSpotifyExpiry() *SessionUpdate {
	su.mutation.ClearSpotifyExpiry()
	return su
}

// SetUserID sets the "user" edge to the User entity by ID.
func (su *SessionUpdate) SetUserID(id int) *SessionUpdate {
	su.mutation.SetUserID(id)
	return su
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (su *SessionUpdate) SetNillableUserID(id *int) *SessionUpdate {
	if id != nil {
		su = su.SetUserID(*id)
	}
	return su
}

// SetUser sets the "user" edge to the User entity.
func (su *SessionUpdate) SetUser(u *User) *SessionUpdate {
	return su.SetUserID(u.ID)
}

// Mutation returns the SessionMutation object of the builder.
func (su *SessionUpdate) Mutation() *SessionMutation {
	return su.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (su *SessionUpdate) ClearUser() *SessionUpdate {
	su.mutation.ClearUser()
	return su
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SessionUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SessionUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SessionUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SessionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Token(); ok {
		_spec.SetField(session.FieldToken, field.TypeString, value)
	}
	if value, ok := su.mutation.IPAddress(); ok {
		_spec.SetField(session.FieldIPAddress, field.TypeString, value)
	}
	if su.mutation.IPAddressCleared() {
		_spec.ClearField(session.FieldIPAddress, field.TypeString)
	}
	if value, ok := su.mutation.UserAgent(); ok {
		_spec.SetField(session.FieldUserAgent, field.TypeString, value)
	}
	if su.mutation.UserAgentCleared() {
		_spec.ClearField(session.FieldUserAgent, field.TypeString)
	}
	if value, ok := su.mutation.ExpiresAt(); ok {
		_spec.SetField(session.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := su.mutation.LastLoginAt(); ok {
		_spec.SetField(session.FieldLastLoginAt, field.TypeTime, value)
	}
	if su.mutation.LastLoginAtCleared() {
		_spec.ClearField(session.FieldLastLoginAt, field.TypeTime)
	}
	if value, ok := su.mutation.SpotifyAccessToken(); ok {
		_spec.SetField(session.FieldSpotifyAccessToken, field.TypeString, value)
	}
	if su.mutation.SpotifyAccessTokenCleared() {
		_spec.ClearField(session.FieldSpotifyAccessToken, field.TypeString)
	}
	if value, ok := su.mutation.SpotifyRefreshToken(); ok {
		_spec.SetField(session.FieldSpotifyRefreshToken, field.TypeString, value)
	}
	if su.mutation.SpotifyRefreshTokenCleared() {
		_spec.ClearField(session.FieldSpotifyRefreshToken, field.TypeString)
	}
	if value, ok := su.mutation.SpotifyExpiry(); ok {
		_spec.SetField(session.FieldSpotifyExpiry, field.TypeTime, value)
	}
	if su.mutation.SpotifyExpiryCleared() {
		_spec.ClearField(session.FieldSpotifyExpiry, field.TypeTime)
	}
	if su.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.UserTable,
			Columns: []string{session.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.UserTable,
			Columns: []string{session.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SessionUpdateOne is the builder for updating a single Session entity.
type SessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMutation
}

// SetToken sets the "token" field.
func (suo *SessionUpdateOne) SetToken(s string) *SessionUpdateOne {
	suo.mutation.SetToken(s)
	return suo
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableToken(s *string) *SessionUpdateOne {
	if s != nil {
		suo.SetToken(*s)
	}
	return suo
}

// SetIPAddress sets the "ip_address" field.
func (suo *SessionUpdateOne) SetIPAddress(s string) *SessionUpdateOne {
	suo.mutation.SetIPAddress(s)
	return suo
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableIPAddress(s *string) *SessionUpdateOne {
	if s != nil {
		suo.SetIPAddress(*s)
	}
	return suo
}

// ClearIPAddress clears the value of the "ip_address" field.
func (suo *SessionUpdateOne) ClearIPAddress() *SessionUpdateOne {
	suo.mutation.ClearIPAddress()
	return suo
}

// SetUserAgent sets the "user_agent" field.
func (suo *SessionUpdateOne) SetUserAgent(s string) *SessionUpdateOne {
	suo.mutation.SetUserAgent(s)
	return suo
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableUserAgent(s *string) *SessionUpdateOne {
	if s != nil {
		suo.SetUserAgent(*s)
	}
	return suo
}

// ClearUserAgent clears the value of the "user_agent" field.
func (suo *SessionUpdateOne) ClearUserAgent() *SessionUpdateOne {
	suo.mutation.ClearUserAgent()
	return suo
}

// SetExpiresAt sets the "expires_at" field.
func (suo *SessionUpdateOne) SetExpiresAt(t time.Time) *SessionUpdateOne {
	suo.mutation.SetExpiresAt(t)
	return suo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableExpiresAt(t *time.Time) *SessionUpdateOne {
	if t != nil {
		suo.SetExpiresAt(*t)
	}
	return suo
}

// SetLastLoginAt sets the "last_login_at" field.
func (suo *SessionUpdateOne) SetLastLoginAt(t time.Time) *SessionUpdateOne {
	suo.mutation.SetLastLoginAt(t)
	return suo
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableLastLoginAt(t *time.Time) *SessionUpdateOne {
	if t != nil {
		suo.SetLastLoginAt(*t)
	}
	return suo
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (suo *SessionUpdateOne) ClearLastLoginAt() *SessionUpdateOne {
	suo.mutation.ClearLastLoginAt()
	return suo
}

// SetSpotifyAccessToken sets the "spotify_access_token" field.
func (suo *SessionUpdateOne) SetSpotifyAccessToken(s string) *SessionUpdateOne {
	suo.mutation.SetSpotifyAccessToken(s)
	return suo
}

// SetNillableSpotifyAccessToken sets the "spotify_access_token" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableSpotifyAccessToken(s *string) *SessionUpdateOne {
	if s != nil {
		suo.SetSpotifyAccessToken(*s)
	}
	return suo
}

// ClearSpotifyAccessToken clears the value of the "spotify_access_token" field.
func (suo *SessionUpdateOne) ClearSpotifyAccessToken() *SessionUpdateOne {
	suo.mutation.ClearSpotifyAccessToken()
	return suo
}

// SetSpotifyRefreshToken sets the "spotify_refresh_token" field.
func (suo *SessionUpdateOne) SetSpotifyRefreshToken(s string) *SessionUpdateOne {
	suo.mutation.SetSpotifyRefreshToken(s)
	return suo
}

// SetNillableSpotifyRefreshToken sets the "spotify_refresh_token" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableSpotifyRefreshToken(s *string) *SessionUpdateOne {
	if s != nil {
		suo.SetSpotifyRefreshToken(*s)
	}
	return suo
}

// ClearSpotifyRefreshToken clears the value of the "spotify_refresh_token" field.
func (suo *SessionUpdateOne) ClearSpotifyRefreshToken() *SessionUpdateOne {
	suo.mutation.ClearSpotifyRefreshToken()
	return suo
}

// SetSpotifyExpiry sets the "spotify_expiry" field.
func (suo *SessionUpdateOne) SetSpotifyExpiry(t time.Time) *SessionUpdateOne {
	suo.mutation.SetSpotifyExpiry(t)
	return suo
}

// SetNillableSpotifyExpiry sets the "spotify_expiry" field if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableSpotifyExpiry(t *time.Time) *SessionUpdateOne {
	if t != nil {
		suo.SetSpotifyExpiry(*t)
	}
	return suo
}

// ClearSpotifyExpiry clears the value of the "spotify_expiry" field.
func (suo *SessionUpdateOne) ClearSpotifyExpiry() *SessionUpdateOne {
	suo.mutation.ClearSpotifyExpiry()
	return suo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (suo *SessionUpdateOne) SetUserID(id int) *SessionUpdateOne {
	suo.mutation.SetUserID(id)
	return suo
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (suo *SessionUpdateOne) SetNillableUserID(id *int) *SessionUpdateOne {
	if id != nil {
		suo = suo.SetUserID(*id)
	}
	return suo
}

// SetUser sets the "user" edge to the User entity.
func (suo *SessionUpdateOne) SetUser(u *User) *SessionUpdateOne {
	return suo.SetUserID(u.ID)
}

// Mutation returns the SessionMutation object of the builder.
func (suo *SessionUpdateOne) Mutation() *SessionMutation {
	return suo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (suo *SessionUpdateOne) ClearUser() *SessionUpdateOne {
	suo.mutation.ClearUser()
	return suo
}

// Where appends a list predicates to the SessionUpdate builder.
func (suo *SessionUpdateOne) Where(ps ...predicate.Session) *SessionUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SessionUpdateOne) Select(field string, fields ...string) *SessionUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Session entity.
func (suo *SessionUpdateOne) Save(ctx context.Context) (*Session, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SessionUpdateOne) SaveX(ctx context.Context) *Session {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SessionUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SessionUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SessionUpdateOne) sqlSave(ctx context.Context) (_node *Session, err error) {
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Session.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, session.FieldID)
		for _, f := range fields {
			if !session.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != session.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Token(); ok {
		_spec.SetField(session.FieldToken, field.TypeString, value)
	}
	if value, ok := suo.mutation.IPAddress(); ok {
		_spec.SetField(session.FieldIPAddress, field.TypeString, value)
	}
	if suo.mutation.IPAddressCleared() {
		_spec.ClearField(session.FieldIPAddress, field.TypeString)
	}
	if value, ok := suo.mutation.UserAgent(); ok {
		_spec.SetField(session.FieldUserAgent, field.TypeString, value)
	}
	if suo.mutation.UserAgentCleared() {
		_spec.ClearField(session.FieldUserAgent, field.TypeString)
	}
	if value, ok := suo.mutation.ExpiresAt(); ok {
		_spec.SetField(session.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := suo.mutation.LastLoginAt(); ok {
		_spec.SetField(session.FieldLastLoginAt, field.TypeTime, value)
	}
	if suo.mutation.LastLoginAtCleared() {
		_spec.ClearField(session.FieldLastLoginAt, field.TypeTime)
	}
	if value, ok := suo.mutation.SpotifyAccessToken(); ok {
		_spec.SetField(session.FieldSpotifyAccessToken, field.TypeString, value)
	}
	if suo.mutation.SpotifyAccessTokenCleared() {
		_spec.ClearField(session.FieldSpotifyAccessToken, field.TypeString)
	}
	if value, ok := suo.mutation.SpotifyRefreshToken(); ok {
		_spec.SetField(session.FieldSpotifyRefreshToken, field.TypeString, value)
	}
	if suo.mutation.SpotifyRefreshTokenCleared() {
		_spec.ClearField(session.FieldSpotifyRefreshToken, field.TypeString)
	}
	if value, ok := suo.mutation.SpotifyExpiry(); ok {
		_spec.SetField(session.FieldSpotifyExpiry, field.TypeTime, value)
	}
	if suo.mutation.SpotifyExpiryCleared() {
		_spec.ClearField(session.FieldSpotifyExpiry, field.TypeTime)
	}
	if suo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.UserTable,
			Columns: []string{session.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.UserTable,
			Columns: []string{session.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Session{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
