// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Pineapple217/Sortify/web/ent/playlist"
	"github.com/Pineapple217/Sortify/web/ent/predicate"
	"github.com/Pineapple217/Sortify/web/ent/track"
)

// TrackUpdate is the builder for updating Track entities.
type TrackUpdate struct {
	config
	hooks    []Hook
	mutation *TrackMutation
}

// Where appends a list predicates to the TrackUpdate builder.
func (tu *TrackUpdate) Where(ps ...predicate.Track) *TrackUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetName sets the "name" field.
func (tu *TrackUpdate) SetName(s string) *TrackUpdate {
	tu.mutation.SetName(s)
	return tu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tu *TrackUpdate) SetNillableName(s *string) *TrackUpdate {
	if s != nil {
		tu.SetName(*s)
	}
	return tu
}

// SetArtist sets the "artist" field.
func (tu *TrackUpdate) SetArtist(s string) *TrackUpdate {
	tu.mutation.SetArtist(s)
	return tu
}

// SetNillableArtist sets the "artist" field if the given value is not nil.
func (tu *TrackUpdate) SetNillableArtist(s *string) *TrackUpdate {
	if s != nil {
		tu.SetArtist(*s)
	}
	return tu
}

// SetImgSmallURL sets the "img_small_url" field.
func (tu *TrackUpdate) SetImgSmallURL(s string) *TrackUpdate {
	tu.mutation.SetImgSmallURL(s)
	return tu
}

// SetNillableImgSmallURL sets the "img_small_url" field if the given value is not nil.
func (tu *TrackUpdate) SetNillableImgSmallURL(s *string) *TrackUpdate {
	if s != nil {
		tu.SetImgSmallURL(*s)
	}
	return tu
}

// ClearImgSmallURL clears the value of the "img_small_url" field.
func (tu *TrackUpdate) ClearImgSmallURL() *TrackUpdate {
	tu.mutation.ClearImgSmallURL()
	return tu
}

// SetImgMediumURL sets the "img_medium_url" field.
func (tu *TrackUpdate) SetImgMediumURL(s string) *TrackUpdate {
	tu.mutation.SetImgMediumURL(s)
	return tu
}

// SetNillableImgMediumURL sets the "img_medium_url" field if the given value is not nil.
func (tu *TrackUpdate) SetNillableImgMediumURL(s *string) *TrackUpdate {
	if s != nil {
		tu.SetImgMediumURL(*s)
	}
	return tu
}

// ClearImgMediumURL clears the value of the "img_medium_url" field.
func (tu *TrackUpdate) ClearImgMediumURL() *TrackUpdate {
	tu.mutation.ClearImgMediumURL()
	return tu
}

// SetImgLargeURL sets the "img_large_url" field.
func (tu *TrackUpdate) SetImgLargeURL(s string) *TrackUpdate {
	tu.mutation.SetImgLargeURL(s)
	return tu
}

// SetNillableImgLargeURL sets the "img_large_url" field if the given value is not nil.
func (tu *TrackUpdate) SetNillableImgLargeURL(s *string) *TrackUpdate {
	if s != nil {
		tu.SetImgLargeURL(*s)
	}
	return tu
}

// ClearImgLargeURL clears the value of the "img_large_url" field.
func (tu *TrackUpdate) ClearImgLargeURL() *TrackUpdate {
	tu.mutation.ClearImgLargeURL()
	return tu
}

// SetReleaseDate sets the "release_date" field.
func (tu *TrackUpdate) SetReleaseDate(t time.Time) *TrackUpdate {
	tu.mutation.SetReleaseDate(t)
	return tu
}

// SetNillableReleaseDate sets the "release_date" field if the given value is not nil.
func (tu *TrackUpdate) SetNillableReleaseDate(t *time.Time) *TrackUpdate {
	if t != nil {
		tu.SetReleaseDate(*t)
	}
	return tu
}

// SetDurationMs sets the "duration_ms" field.
func (tu *TrackUpdate) SetDurationMs(i int) *TrackUpdate {
	tu.mutation.ResetDurationMs()
	tu.mutation.SetDurationMs(i)
	return tu
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (tu *TrackUpdate) SetNillableDurationMs(i *int) *TrackUpdate {
	if i != nil {
		tu.SetDurationMs(*i)
	}
	return tu
}

// AddDurationMs adds i to the "duration_ms" field.
func (tu *TrackUpdate) AddDurationMs(i int) *TrackUpdate {
	tu.mutation.AddDurationMs(i)
	return tu
}

// SetPreviewURL sets the "preview_url" field.
func (tu *TrackUpdate) SetPreviewURL(s string) *TrackUpdate {
	tu.mutation.SetPreviewURL(s)
	return tu
}

// SetNillablePreviewURL sets the "preview_url" field if the given value is not nil.
func (tu *TrackUpdate) SetNillablePreviewURL(s *string) *TrackUpdate {
	if s != nil {
		tu.SetPreviewURL(*s)
	}
	return tu
}

// ClearPreviewURL clears the value of the "preview_url" field.
func (tu *TrackUpdate) ClearPreviewURL() *TrackUpdate {
	tu.mutation.ClearPreviewURL()
	return tu
}

// SetPopularity sets the "popularity" field.
func (tu *TrackUpdate) SetPopularity(i int) *TrackUpdate {
	tu.mutation.ResetPopularity()
	tu.mutation.SetPopularity(i)
	return tu
}

// SetNillablePopularity sets the "popularity" field if the given value is not nil.
func (tu *TrackUpdate) SetNillablePopularity(i *int) *TrackUpdate {
	if i != nil {
		tu.SetPopularity(*i)
	}
	return tu
}

// AddPopularity adds i to the "popularity" field.
func (tu *TrackUpdate) AddPopularity(i int) *TrackUpdate {
	tu.mutation.AddPopularity(i)
	return tu
}

// SetUpdatedAt sets the "updated_at" field.
func (tu *TrackUpdate) SetUpdatedAt(t time.Time) *TrackUpdate {
	tu.mutation.SetUpdatedAt(t)
	return tu
}

// SetDeletedAt sets the "deleted_at" field.
func (tu *TrackUpdate) SetDeletedAt(t time.Time) *TrackUpdate {
	tu.mutation.SetDeletedAt(t)
	return tu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (tu *TrackUpdate) SetNillableDeletedAt(t *time.Time) *TrackUpdate {
	if t != nil {
		tu.SetDeletedAt(*t)
	}
	return tu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (tu *TrackUpdate) ClearDeletedAt() *TrackUpdate {
	tu.mutation.ClearDeletedAt()
	return tu
}

// AddPlaylistIDs adds the "playlists" edge to the Playlist entity by IDs.
func (tu *TrackUpdate) AddPlaylistIDs(ids ...int) *TrackUpdate {
	tu.mutation.AddPlaylistIDs(ids...)
	return tu
}

// AddPlaylists adds the "playlists" edges to the Playlist entity.
func (tu *TrackUpdate) AddPlaylists(p ...*Playlist) *TrackUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return tu.AddPlaylistIDs(ids...)
}

// Mutation returns the TrackMutation object of the builder.
func (tu *TrackUpdate) Mutation() *TrackMutation {
	return tu.mutation
}

// ClearPlaylists clears all "playlists" edges to the Playlist entity.
func (tu *TrackUpdate) ClearPlaylists() *TrackUpdate {
	tu.mutation.ClearPlaylists()
	return tu
}

// RemovePlaylistIDs removes the "playlists" edge to Playlist entities by IDs.
func (tu *TrackUpdate) RemovePlaylistIDs(ids ...int) *TrackUpdate {
	tu.mutation.RemovePlaylistIDs(ids...)
	return tu
}

// RemovePlaylists removes "playlists" edges to Playlist entities.
func (tu *TrackUpdate) RemovePlaylists(p ...*Playlist) *TrackUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return tu.RemovePlaylistIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TrackUpdate) Save(ctx context.Context) (int, error) {
	tu.defaults()
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TrackUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TrackUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TrackUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tu *TrackUpdate) defaults() {
	if _, ok := tu.mutation.UpdatedAt(); !ok {
		v := track.UpdateDefaultUpdatedAt()
		tu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TrackUpdate) check() error {
	if v, ok := tu.mutation.DurationMs(); ok {
		if err := track.DurationMsValidator(v); err != nil {
			return &ValidationError{Name: "duration_ms", err: fmt.Errorf(`ent: validator failed for field "Track.duration_ms": %w`, err)}
		}
	}
	return nil
}

func (tu *TrackUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(track.Table, track.Columns, sqlgraph.NewFieldSpec(track.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Name(); ok {
		_spec.SetField(track.FieldName, field.TypeString, value)
	}
	if value, ok := tu.mutation.Artist(); ok {
		_spec.SetField(track.FieldArtist, field.TypeString, value)
	}
	if value, ok := tu.mutation.ImgSmallURL(); ok {
		_spec.SetField(track.FieldImgSmallURL, field.TypeString, value)
	}
	if tu.mutation.ImgSmallURLCleared() {
		_spec.ClearField(track.FieldImgSmallURL, field.TypeString)
	}
	if value, ok := tu.mutation.ImgMediumURL(); ok {
		_spec.SetField(track.FieldImgMediumURL, field.TypeString, value)
	}
	if tu.mutation.ImgMediumURLCleared() {
		_spec.ClearField(track.FieldImgMediumURL, field.TypeString)
	}
	if value, ok := tu.mutation.ImgLargeURL(); ok {
		_spec.SetField(track.FieldImgLargeURL, field.TypeString, value)
	}
	if tu.mutation.ImgLargeURLCleared() {
		_spec.ClearField(track.FieldImgLargeURL, field.TypeString)
	}
	if value, ok := tu.mutation.ReleaseDate(); ok {
		_spec.SetField(track.FieldReleaseDate, field.TypeTime, value)
	}
	if value, ok := tu.mutation.DurationMs(); ok {
		_spec.SetField(track.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedDurationMs(); ok {
		_spec.AddField(track.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := tu.mutation.PreviewURL(); ok {
		_spec.SetField(track.FieldPreviewURL, field.TypeString, value)
	}
	if tu.mutation.PreviewURLCleared() {
		_spec.ClearField(track.FieldPreviewURL, field.TypeString)
	}
	if value, ok := tu.mutation.Popularity(); ok {
		_spec.SetField(track.FieldPopularity, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedPopularity(); ok {
		_spec.AddField(track.FieldPopularity, field.TypeInt, value)
	}
	if value, ok := tu.mutation.UpdatedAt(); ok {
		_spec.SetField(track.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.DeletedAt(); ok {
		_spec.SetField(track.FieldDeletedAt, field.TypeTime, value)
	}
	if tu.mutation.DeletedAtCleared() {
		_spec.ClearField(track.FieldDeletedAt, field.TypeTime)
	}
	if tu.mutation.PlaylistsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   track.PlaylistsTable,
			Columns: track.PlaylistsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedPlaylistsIDs(); len(nodes) > 0 && !tu.mutation.PlaylistsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   track.PlaylistsTable,
			Columns: track.PlaylistsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.PlaylistsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   track.PlaylistsTable,
			Columns: track.PlaylistsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{track.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TrackUpdateOne is the builder for updating a single Track entity.
type TrackUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TrackMutation
}

// SetName sets the "name" field.
func (tuo *TrackUpdateOne) SetName(s string) *TrackUpdateOne {
	tuo.mutation.SetName(s)
	return tuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tuo *TrackUpdateOne) SetNillableName(s *string) *TrackUpdateOne {
	if s != nil {
		tuo.SetName(*s)
	}
	return tuo
}

// SetArtist sets the "artist" field.
func (tuo *TrackUpdateOne) SetArtist(s string) *TrackUpdateOne {
	tuo.mutation.SetArtist(s)
	return tuo
}

// SetNillableArtist sets the "artist" field if the given value is not nil.
func (tuo *TrackUpdateOne) SetNillableArtist(s *string) *TrackUpdateOne {
	if s != nil {
		tuo.SetArtist(*s)
	}
	return tuo
}

// SetImgSmallURL sets the "img_small_url" field.
func (tuo *TrackUpdateOne) SetImgSmallURL(s string) *TrackUpdateOne {
	tuo.mutation.SetImgSmallURL(s)
	return tuo
}

// SetNillableImgSmallURL sets the "img_small_url" field if the given value is not nil.
func (tuo *TrackUpdateOne) SetNillableImgSmallURL(s *string) *TrackUpdateOne {
	if s != nil {
		tuo.SetImgSmallURL(*s)
	}
	return tuo
}

// ClearImgSmallURL clears the value of the "img_small_url" field.
func (tuo *TrackUpdateOne) ClearImgSmallURL() *TrackUpdateOne {
	tuo.mutation.ClearImgSmallURL()
	return tuo
}

// SetImgMediumURL sets the "img_medium_url" field.
func (tuo *TrackUpdateOne) SetImgMediumURL(s string) *TrackUpdateOne {
	tuo.mutation.SetImgMediumURL(s)
	return tuo
}

// SetNillableImgMediumURL sets the "img_medium_url" field if the given value is not nil.
func (tuo *TrackUpdateOne) SetNillableImgMediumURL(s *string) *TrackUpdateOne {
	if s != nil {
		tuo.SetImgMediumURL(*s)
	}
	return tuo
}

// ClearImgMediumURL clears the value of the "img_medium_url" field.
func (tuo *TrackUpdateOne) ClearImgMediumURL() *TrackUpdateOne {
	tuo.mutation.ClearImgMediumURL()
	return tuo
}

// SetImgLargeURL sets the "img_large_url" field.
func (tuo *TrackUpdateOne) SetImgLargeURL(s string) *TrackUpdateOne {
	tuo.mutation.SetImgLargeURL(s)
	return tuo
}

// SetNillableImgLargeURL sets the "img_large_url" field if the given value is not nil.
func (tuo *TrackUpdateOne) SetNillableImgLargeURL(s *string) *TrackUpdateOne {
	if s != nil {
		tuo.SetImgLargeURL(*s)
	}
	return tuo
}

// ClearImgLargeURL clears the value of the "img_large_url" field.
func (tuo *TrackUpdateOne) ClearImgLargeURL() *TrackUpdateOne {
	tuo.mutation.ClearImgLargeURL()
	return tuo
}

// SetReleaseDate sets the "release_date" field.
func (tuo *TrackUpdateOne) SetReleaseDate(t time.Time) *TrackUpdateOne {
	tuo.mutation.SetReleaseDate(t)
	return tuo
}

// SetNillableReleaseDate sets the "release_date" field if the given value is not nil.
func (tuo *TrackUpdateOne) SetNillableReleaseDate(t *time.Time) *TrackUpdateOne {
	if t != nil {
		tuo.SetReleaseDate(*t)
	}
	return tuo
}

// SetDurationMs sets the "duration_ms" field.
func (tuo *TrackUpdateOne) SetDurationMs(i int) *TrackUpdateOne {
	tuo.mutation.ResetDurationMs()
	tuo.mutation.SetDurationMs(i)
	return tuo
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (tuo *TrackUpdateOne) SetNillableDurationMs(i *int) *TrackUpdateOne {
	if i != nil {
		tuo.SetDurationMs(*i)
	}
	return tuo
}

// AddDurationMs adds i to the "duration_ms" field.
func (tuo *TrackUpdateOne) AddDurationMs(i int) *TrackUpdateOne {
	tuo.mutation.AddDurationMs(i)
	return tuo
}

// SetPreviewURL sets the "preview_url" field.
func (tuo *TrackUpdateOne) SetPreviewURL(s string) *TrackUpdateOne {
	tuo.mutation.SetPreviewURL(s)
	return tuo
}

// SetNillablePreviewURL sets the "preview_url" field if the given value is not nil.
func (tuo *TrackUpdateOne) SetNillablePreviewURL(s *string) *TrackUpdateOne {
	if s != nil {
		tuo.SetPreviewURL(*s)
	}
	return tuo
}

// ClearPreviewURL clears the value of the "preview_url" field.
func (tuo *TrackUpdateOne) ClearPreviewURL() *TrackUpdateOne {
	tuo.mutation.ClearPreviewURL()
	return tuo
}

// SetPopularity sets the "popularity" field.
func (tuo *TrackUpdateOne) SetPopularity(i int) *TrackUpdateOne {
	tuo.mutation.ResetPopularity()
	tuo.mutation.SetPopularity(i)
	return tuo
}

// SetNillablePopularity sets the "popularity" field if the given value is not nil.
func (tuo *TrackUpdateOne) SetNillablePopularity(i *int) *TrackUpdateOne {
	if i != nil {
		tuo.SetPopularity(*i)
	}
	return tuo
}

// AddPopularity adds i to the "popularity" field.
func (tuo *TrackUpdateOne) AddPopularity(i int) *TrackUpdateOne {
	tuo.mutation.AddPopularity(i)
	return tuo
}

// SetUpdatedAt sets the "updated_at" field.
func (tuo *TrackUpdateOne) SetUpdatedAt(t time.Time) *TrackUpdateOne {
	tuo.mutation.SetUpdatedAt(t)
	return tuo
}

// SetDeletedAt sets the "deleted_at" field.
func (tuo *TrackUpdateOne) SetDeletedAt(t time.Time) *TrackUpdateOne {
	tuo.mutation.SetDeletedAt(t)
	return tuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (tuo *TrackUpdateOne) SetNillableDeletedAt(t *time.Time) *TrackUpdateOne {
	if t != nil {
		tuo.SetDeletedAt(*t)
	}
	return tuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (tuo *TrackUpdateOne) ClearDeletedAt() *TrackUpdateOne {
	tuo.mutation.ClearDeletedAt()
	return tuo
}

// AddPlaylistIDs adds the "playlists" edge to the Playlist entity by IDs.
func (tuo *TrackUpdateOne) AddPlaylistIDs(ids ...int) *TrackUpdateOne {
	tuo.mutation.AddPlaylistIDs(ids...)
	return tuo
}

// AddPlaylists adds the "playlists" edges to the Playlist entity.
func (tuo *TrackUpdateOne) AddPlaylists(p ...*Playlist) *TrackUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return tuo.AddPlaylistIDs(ids...)
}

// Mutation returns the TrackMutation object of the builder.
func (tuo *TrackUpdateOne) Mutation() *TrackMutation {
	return tuo.mutation
}

// ClearPlaylists clears all "playlists" edges to the Playlist entity.
func (tuo *TrackUpdateOne) ClearPlaylists() *TrackUpdateOne {
	tuo.mutation.ClearPlaylists()
	return tuo
}

// RemovePlaylistIDs removes the "playlists" edge to Playlist entities by IDs.
func (tuo *TrackUpdateOne) RemovePlaylistIDs(ids ...int) *TrackUpdateOne {
	tuo.mutation.RemovePlaylistIDs(ids...)
	return tuo
}

// RemovePlaylists removes "playlists" edges to Playlist entities.
func (tuo *TrackUpdateOne) RemovePlaylists(p ...*Playlist) *TrackUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return tuo.RemovePlaylistIDs(ids...)
}

// Where appends a list predicates to the TrackUpdate builder.
func (tuo *TrackUpdateOne) Where(ps ...predicate.Track) *TrackUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TrackUpdateOne) Select(field string, fields ...string) *TrackUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Track entity.
func (tuo *TrackUpdateOne) Save(ctx context.Context) (*Track, error) {
	tuo.defaults()
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TrackUpdateOne) SaveX(ctx context.Context) *Track {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TrackUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TrackUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tuo *TrackUpdateOne) defaults() {
	if _, ok := tuo.mutation.UpdatedAt(); !ok {
		v := track.UpdateDefaultUpdatedAt()
		tuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TrackUpdateOne) check() error {
	if v, ok := tuo.mutation.DurationMs(); ok {
		if err := track.DurationMsValidator(v); err != nil {
			return &ValidationError{Name: "duration_ms", err: fmt.Errorf(`ent: validator failed for field "Track.duration_ms": %w`, err)}
		}
	}
	return nil
}

func (tuo *TrackUpdateOne) sqlSave(ctx context.Context) (_node *Track, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(track.Table, track.Columns, sqlgraph.NewFieldSpec(track.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Track.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, track.FieldID)
		for _, f := range fields {
			if !track.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != track.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Name(); ok {
		_spec.SetField(track.FieldName, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Artist(); ok {
		_spec.SetField(track.FieldArtist, field.TypeString, value)
	}
	if value, ok := tuo.mutation.ImgSmallURL(); ok {
		_spec.SetField(track.FieldImgSmallURL, field.TypeString, value)
	}
	if tuo.mutation.ImgSmallURLCleared() {
		_spec.ClearField(track.FieldImgSmallURL, field.TypeString)
	}
	if value, ok := tuo.mutation.ImgMediumURL(); ok {
		_spec.SetField(track.FieldImgMediumURL, field.TypeString, value)
	}
	if tuo.mutation.ImgMediumURLCleared() {
		_spec.ClearField(track.FieldImgMediumURL, field.TypeString)
	}
	if value, ok := tuo.mutation.ImgLargeURL(); ok {
		_spec.SetField(track.FieldImgLargeURL, field.TypeString, value)
	}
	if tuo.mutation.ImgLargeURLCleared() {
		_spec.ClearField(track.FieldImgLargeURL, field.TypeString)
	}
	if value, ok := tuo.mutation.ReleaseDate(); ok {
		_spec.SetField(track.FieldReleaseDate, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.DurationMs(); ok {
		_spec.SetField(track.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedDurationMs(); ok {
		_spec.AddField(track.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.PreviewURL(); ok {
		_spec.SetField(track.FieldPreviewURL, field.TypeString, value)
	}
	if tuo.mutation.PreviewURLCleared() {
		_spec.ClearField(track.FieldPreviewURL, field.TypeString)
	}
	if value, ok := tuo.mutation.Popularity(); ok {
		_spec.SetField(track.FieldPopularity, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedPopularity(); ok {
		_spec.AddField(track.FieldPopularity, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.UpdatedAt(); ok {
		_spec.SetField(track.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.DeletedAt(); ok {
		_spec.SetField(track.FieldDeletedAt, field.TypeTime, value)
	}
	if tuo.mutation.DeletedAtCleared() {
		_spec.ClearField(track.FieldDeletedAt, field.TypeTime)
	}
	if tuo.mutation.PlaylistsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   track.PlaylistsTable,
			Columns: track.PlaylistsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedPlaylistsIDs(); len(nodes) > 0 && !tuo.mutation.PlaylistsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   track.PlaylistsTable,
			Columns: track.PlaylistsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.PlaylistsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   track.PlaylistsTable,
			Columns: track.PlaylistsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Track{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{track.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
