// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID                  int64
	UserID              int64
	Token               string
	IpAddress           pgtype.Text
	UserAgent           pgtype.Text
	ExpiresAt           pgtype.Timestamptz
	LastLoginAt         pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	SpotifyAccessToken  pgtype.Text
	SpotifyRefreshToken pgtype.Text
	SpotifyExpiry       pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
