// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Playlist struct {
	ID        int64
	Title     string
	UserID    int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type PlaylistTrack struct {
	ID         int64
	PlaylistID int64
	TrackID    int64
	AddedAt    pgtype.Timestamptz
}

type Session struct {
	ID                  int64
	UserID              int64
	Token               string
	IpAddress           pgtype.Text
	UserAgent           pgtype.Text
	ExpiresAt           pgtype.Timestamptz
	LastLoginAt         pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	SpotifyAccessToken  pgtype.Text
	SpotifyRefreshToken pgtype.Text
	SpotifyExpiry       pgtype.Timestamptz
}

type Track struct {
	ID           int64
	Title        string
	Artist       string
	ImgSmallUrl  pgtype.Text
	ImgMediumUrl pgtype.Text
	ImgLargeUrl  pgtype.Text
	ReleaseDate  pgtype.Date
	SpotifyID    string
	DurationMs   int32
	PreviewUrl   pgtype.Text
	Popularity   int16
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
